# Generated by Django 6.0 on 2026-01-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_habilidad_nivel_habilidad_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_obtencion']},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-inicio']},
        ),
    ]
