# Generated by Django 6.0 on 2026-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_certificado_options_alter_experiencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('reconocimiento', 'Reconocimiento')], default='curso', max_length=20),
        ),
    ]
