# Generated by Django 6.0 on 2026-01-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_certificado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cv.certificado',),
        ),
        migrations.CreateModel(
            name='ReconocimientoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cv.certificado',),
        ),
    ]
