# Generated by Django 6.0 on 2026-01-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_cursoproxy_reconocimientoproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='total_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Solo para cursos', null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('reconocimiento', 'Reconocimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='inicio',
            field=models.DateField(),
        ),
    ]
