# Generated by Django 6.0 on 2026-02-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_certificado_total_horas_alter_certificado_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.perfil')),
            ],
            options={
                'db_table': 'productosacademicos',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.perfil')),
            ],
            options={
                'db_table': 'productoslaborales',
            },
        ),
        migrations.CreateModel(
            name='VentaGaraje',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='cv.perfil')),
            ],
            options={
                'db_table': 'ventagarage',
            },
        ),
    ]
