# Generated by Django 6.0 on 2026-01-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_certificado_total_horas_alter_certificado_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaGaraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo_front', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.perfil')),
            ],
        ),
    ]
