# Generated by Django 6.0 on 2026-01-31 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_ventagaraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagaraje',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventagaraje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='venta_garaje/'),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='estado_producto',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Semi-nuevo', 'Semi-nuevo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='nombre_producto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garaje', to='cv.perfil'),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='valor_bien',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
