# Generated by Django 6.0 on 2026-02-01 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_ventagaraje_fecha_publicacion_ventagaraje_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventagaraje',
            name='activo_front',
        ),
        migrations.RemoveField(
            model_name='ventagaraje',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='estado_producto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='nombre_producto',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='productos_academicos/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.perfil')),
            ],
        ),
    ]
