# Generated by Django 6.0 on 2026-02-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_remove_ventagaraje_activo_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_academicos/img/'),
        ),
    ]
