# Generated by Django 6.0 on 2026-02-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_productoacademico_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoacademico',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='titulo',
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='nombre_recurso',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
