# Generated by Django 6.0 on 2026-02-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_remove_productoacademico_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoacademico',
            old_name='activo',
            new_name='activarparaqueseveaenfront',
        ),
        migrations.RenameField(
            model_name='productoacademico',
            old_name='nombre_recurso',
            new_name='nombrerecurso',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_academicos/'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
