# Generated by Django 6.0 on 2026-02-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_rename_activo_productoacademico_activarparaqueseveaenfront_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoacademico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='imagen',
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='clasificador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.perfil'),
        ),
        migrations.AlterModelTable(
            name='productoacademico',
            table='productosacademicos',
        ),
    ]
