# Generated by Django 6.0 on 2026-02-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_productolaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('curso', 'Curso'), ('certificacion', 'Certificación'), ('reconocimiento', 'Reconocimiento')], max_length=20),
        ),
    ]
