# Generated by Django 6.0 on 2026-02-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_productoacademico_productolaboral_ventagaraje'),
        ('cv', '0022_productolaboral'),
    ]

    operations = [
    ]
